# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1325ed7dad45735d83f7045dbdd611f6"
name = "thank-pdf-link"
application_url = "https://summit-legendary-chem-curtis.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [ "https://summit-legendary-chem-curtis.trycloudflare.com/api/auth" ]
